### PR TITLE
Add build guide

### PR DESCRIPTION
**Pull request by swift502**
When contributing I found it useful to build the site locally and test links and such. It's cool to have a little guide for people who might not be familiar with mkdocs.

Let me know what you think!

### CODE REVIEW

**Comment by swift502** [comment]
The build check is failing but I don't think it's my fault right?

**Comment by ucupumar** [comment]
I see, actually, I'm not that familiar with mkdocs, @agnira is the one who usually does all the settings. I can add you to be a collaborator if you want to so you don't have to keep doing pull requests. What do you think?

**Comment by ucupumar** [comment]
Wait I forgot to merge it, I'm sorry

**Comment by swift502** [comment]
@ucupumar Thanks!

> I see, actually, I'm not that familiar with mkdocs, @agnira is the one who usually does all the settings. I can add you to be a collaborator if you want to so you don't have to keep doing pull requests. What do you think?

I don't think a collaborator access is necessary. I don't plan to contribute that much. Maybe one more PR and I'll be done.
Either way you guys are the maintainers, I think you should always review all the changes.

**Comment by ucupumar** [comment]
I see, that's fine. Thanks for your support! :)

**Pull request merged**
